services:
  - type: web
    name: 2nb-digital-backend
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_EXPIRES_IN
        value: 7d

databases:
  - name: 2nb-digital-db
    plan: free
